// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vermillion.EntryExit.Domain.Data;

#nullable disable

namespace Vermillion.EntryExit.Domain.Migrations
{
    [DbContext(typeof(EntryExitDbContext))]
    [Migration("20251209170548_Initial_NamedObjects")]
    partial class Initial_NamedObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("entryexit")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectContractors", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ContractorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("ProjectId", "ContractorId")
                        .HasName("PK_ProjectContractors");

                    b.HasIndex("ContractorId");

                    b.ToTable("ProjectContractors", "entryexit");
                });

            modelBuilder.Entity("Vermillion.EntryExit.Domain.Models.Entities.Contractor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Contractors");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Contractors_Name");

                    b.ToTable("Contractors", "entryexit");
                });

            modelBuilder.Entity("Vermillion.EntryExit.Domain.Models.Entities.EntryExitRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Gate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LabourId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PersonType")
                        .HasColumnType("int");

                    b.Property<string>("RecordedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("VisitorId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_EntryExitRecords");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("IX_EntryExitRecords_ClientId")
                        .HasFilter("[ClientId] IS NOT NULL");

                    b.HasIndex("LabourId", "Action", "Timestamp")
                        .HasDatabaseName("IX_EntryExitRecords_LabourId_Action_Timestamp");

                    b.HasIndex("VisitorId", "Action", "Timestamp")
                        .HasDatabaseName("IX_EntryExitRecords_VisitorId_Action_Timestamp");

                    b.ToTable("EntryExitRecords", "entryexit", t =>
                        {
                            t.HasCheckConstraint("CK_EntryExitRecord_PersonType", "(PersonType = 1 AND LabourId IS NOT NULL AND VisitorId IS NULL) OR (PersonType = 2 AND VisitorId IS NOT NULL AND LabourId IS NULL)");
                        });
                });

            modelBuilder.Entity("Vermillion.EntryExit.Domain.Models.Entities.GuardProjectAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AuthUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_GuardProjectAssignments");

                    b.HasIndex("ProjectId");

                    b.HasIndex("AuthUserId", "ProjectId")
                        .IsUnique()
                        .HasDatabaseName("IX_GuardProjectAssignments_AuthUserId_ProjectId");

                    b.ToTable("GuardProjectAssignments", "entryexit");
                });

            modelBuilder.Entity("Vermillion.EntryExit.Domain.Models.Entities.Labour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AadharNumberEncrypted")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ClassificationId")
                        .HasColumnType("int");

                    b.Property<int>("ContractorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PanNumberEncrypted")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Labours");

                    b.HasIndex("ClassificationId");

                    b.HasIndex("ContractorId");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_Labours_PhoneNumber");

                    b.HasIndex("ProjectId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("IX_Labours_ProjectId_Barcode");

                    b.ToTable("Labours", "entryexit");
                });

            modelBuilder.Entity("Vermillion.EntryExit.Domain.Models.Entities.LabourClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_LabourClassifications");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_LabourClassifications_Name");

                    b.ToTable("LabourClassifications", "entryexit");
                });

            modelBuilder.Entity("Vermillion.EntryExit.Domain.Models.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Projects");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Projects_Name");

                    b.ToTable("Projects", "entryexit");
                });

            modelBuilder.Entity("Vermillion.EntryExit.Domain.Models.Entities.Visitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Visitors");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_Visitors_PhoneNumber");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_Visitors_ProjectId");

                    b.ToTable("Visitors", "entryexit");
                });

            modelBuilder.Entity("ProjectContractors", b =>
                {
                    b.HasOne("Vermillion.EntryExit.Domain.Models.Entities.Contractor", null)
                        .WithMany()
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectContractors_Contractors_ContractorId");

                    b.HasOne("Vermillion.EntryExit.Domain.Models.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectContractors_Projects_ProjectId");
                });

            modelBuilder.Entity("Vermillion.EntryExit.Domain.Models.Entities.EntryExitRecord", b =>
                {
                    b.HasOne("Vermillion.EntryExit.Domain.Models.Entities.Labour", "Labour")
                        .WithMany("EntryExitRecords")
                        .HasForeignKey("LabourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_EntryExitRecords_Labours_LabourId");

                    b.HasOne("Vermillion.EntryExit.Domain.Models.Entities.Visitor", "Visitor")
                        .WithMany("EntryExitRecords")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_EntryExitRecords_Visitors_VisitorId");

                    b.Navigation("Labour");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("Vermillion.EntryExit.Domain.Models.Entities.GuardProjectAssignment", b =>
                {
                    b.HasOne("Vermillion.EntryExit.Domain.Models.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GuardProjectAssignments_Projects_ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Vermillion.EntryExit.Domain.Models.Entities.Labour", b =>
                {
                    b.HasOne("Vermillion.EntryExit.Domain.Models.Entities.LabourClassification", "Classification")
                        .WithMany("Labours")
                        .HasForeignKey("ClassificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Labours_LabourClassifications_ClassificationId");

                    b.HasOne("Vermillion.EntryExit.Domain.Models.Entities.Contractor", "Contractor")
                        .WithMany()
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Labours_Contractors_ContractorId");

                    b.HasOne("Vermillion.EntryExit.Domain.Models.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Labours_Projects_ProjectId");

                    b.Navigation("Classification");

                    b.Navigation("Contractor");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Vermillion.EntryExit.Domain.Models.Entities.Visitor", b =>
                {
                    b.HasOne("Vermillion.EntryExit.Domain.Models.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Visitors_Projects_ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Vermillion.EntryExit.Domain.Models.Entities.Labour", b =>
                {
                    b.Navigation("EntryExitRecords");
                });

            modelBuilder.Entity("Vermillion.EntryExit.Domain.Models.Entities.LabourClassification", b =>
                {
                    b.Navigation("Labours");
                });

            modelBuilder.Entity("Vermillion.EntryExit.Domain.Models.Entities.Visitor", b =>
                {
                    b.Navigation("EntryExitRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
